name: Java CI/CD with Maven and Docker

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Set up application.yml
        run: |
          cat << EOF > ./src/main/resources/application.yml
          spring:
            profiles:
              active: prod
            datasource:
              url: ${{ secrets.MYSQL_URL }}
              username: ${{ secrets.MYSQL_USERNAME }}
              password: ${{ secrets.MYSQL_PASSWORD }}
              driver-class-name: com.mysql.cj.jdbc.Driver
          EOF

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: web docker build and push
        if: github.event_name == 'push'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }} .
          docker push ${{ secrets.DOCKER_REPO }}

      - name: executing remote ssh commands using password
        if: github.event_name == 'push'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stop sensor-api
            docker rm -f sensor-api
            docker rmi $(docker images ${{ secrets.DOCKER_REPO }} -q)
            docker pull ${{ secrets.DOCKER_REPO }}
            docker run -d -p 8080:8080 --name sensor-api ${{ secrets.DOCKER_REPO }}
